[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "eaf5085e2800a3f6879d204e5f0c13ac4b42ccb9"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "365a31f751dad60a56bf98b0b7d0b51cf42e7d67d1c0d79fe0c11803b001f287"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73f49c240bf277c73050596f84129f77df5380ec"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "90376d4443243b742fe6d2b379644a6e4a898b920fbeb0377f65576758eddcd8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71f986d56ae3653cf900b3f30877e703da161f5f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "843315c3e4b4e3ef66527539ec8a672bdf06e006dd14093746df8065d10c9496"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "021e0b693573e3ea7766739b80a5bc6c792658fe"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "a9006d35c5c8c074815eecbf094e73d1df738dbfdd71cb36e0bc47c0e72d81c2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b7a24f5994fbb9e9f860e9ca3b4179b13679776"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "290c105ec8c902fcb2941e2c90f0364db70213daa319ccf22e6b07dd2b85d06f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f58d7c2f12c823b176e3062c004dbd1f62982085"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "6105734edc4c6d9899c3b85580f9b2e02e52a16c436a7d53fc8ccf7fa43edf38"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e1fc2ea724b36ea20f01043446dde695e00566f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "d8a26fdd2369989260f828a66ad1bfe378ed31d96ee1024ddbbadb73c0df494b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "7cd451dd2c3caf50fade835318cd07c9eaa032f6"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "f9c7a1041b7768ed5203f21bce4cb508ffbde83926220afa0eb59c96f6376ae5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ce0398b9e8ffaec962d43bfe7c77588099d7854"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "5c5ccbb7ecb1db889142c2d8c15c35d2040127681d181129965410148edc7b90"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c95ad375dd7eb8f13af7d89bf46ff2297815642f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "ac848559c1e9d50305981c009cbe2c5c0a8ab273e5070e2aed38991e0e5f5902"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ae83f0a71979d3ac738631072112f937f8e0048"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "d28454e288eda060e2e7399ee71b9185dec62c3ffa2e12d258c136b226eba3d2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84ca9c5817fe00ad3dd3e43e2525da1a092d1aeb"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "8cabd818e1770f335f7a993841c83db4c26d0c0a6a1fa69971ce5197909c1446"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "6d49a528114b6d0de7067974198eafa5f0734481"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "268e26c832c9b63358fe25caa662dcb083690bc8cd4f85c9d471badcc739a79a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.400+0/GAP_pkg_normalizinterface.v100.300.400.x86_64-unknown-freebsd.tar.gz"
