[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "02c2cb232b46f0fb14d83029700e02fd91678201"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "72bc124c5cbec8297229694aa944af63247dfaf933c970077061e71690606353"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "305419c0fc7e767c6735015fd2d247314d46fd06"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "01e7357e2a8b96aa5f1cf5fbd4afbd891727f0b85f6bd8ec75a7df090c99ad5d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4d32b8e27be259801249b2a9521f82d381fadba"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "5e969207cf7c9d5a7d1e9c9fba235ccd52793dec2ee4bf3fa02ea6033d079fe4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8a600671ff74a3c686199c479d63e00f6866da6"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "8098616f9396d7ab634abfb1a54574ffb6a92397c8136a93202c69a6a3027b63"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3299fa3973c0a464d5cf5bce460f7abc85d510f9"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "5e5cefab7ea8498c84470aaa1cd92812df766b660302f1ba384a8f0c7f7897f8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2b342ee282a407fc0104e96fea057f07c452cec"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "72a3a59734611447c9e2220238aaa096949c1fd3638e74edd850d56664d33d3f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f39f1f24a84a3c103b1dc5a4b9d49c3ba5e7eb56"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "18886478a5e22d5d2a4cff62ca09ecfaa9e4cd978b9ea88079f69fa0553c76e0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "76f23b167ca3b83c8211a5754ec6cfa9099c0915"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "a31acd18ed159638d79dd817d287909c968c633c74d0c8a886fceda0ec8cd001"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "700255640476c919cefcfd8a2a801a69fa6e10de"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "ddd5e2e21100bbb11aca35c9f7db88366512f832687895477102efd3a1c55392"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f836762be82702e0b3300f615e9f577a0cc2a8c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "17f0c029d28db6cbf00fc96f77abda432bb5906ef4471057dce350a391a987d4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7c95b2e07e1d5fa676786bbd6bb0c5496d272c2"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "a129416ca267d9a92683a62f5313772aa1210cc89150d65da4873bcefb031d73"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "674f82f9428c230d73f433e10d56efd4e983d7bf"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "34503915c95c53595c50819e84f4e479aad2ac68d36efa6ad2c6b7b27381bd24"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "72e706ddf82e0f623d8a5d234d9b5a960f21a103"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "9fef22d969fd196f3d38dbc15a3056b7dc61ecc92379807bc67209430e8d3429"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.701+0/GAP_pkg_normalizinterface.v100.300.701.x86_64-unknown-freebsd.tar.gz"
