[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "5038c005e5427630860524c77de73b4302b2b315"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "3cd84a8da755251706faabfc41ac19bc5133f3a4e8fe46a19f1affd650ef45d9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e70be4a91accbbe8d7efaa7ef2dedb2a63c45dec"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "d1a6c1d7fae6ea05d49c8ec42e0baa6dd220d05f5d8491abe71e2ee37d087045"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61a3c980a2571e3459a1c51c351f20e98146c972"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "8f7ed87b89be076e9c8999350c00fe5deac8231c235cc224314e145e426433eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c0766719802d7cb4b694e2bf4eda74552a4e5f9"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "1fe8a37d9f57f80816072738f645d1275d1972dd2e5ce6b51743a5c61c1db5c3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4aa6ce7816fdcef6b0dd0eb6354daa6fce391d7"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "45fc51c2c520688832f2a011b34fcb489317ac67614f28a1e667610c078a2bfa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "536f39c3d500f454c7574246625b02b6601055c0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "2bb08ce53c40810626c7c89f28cdb706733a8412bc7fd5d9bc34059cbce5a6e1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a239b31e019916716407c4e53c77a8cd550564ef"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "103d6402b04ca119304707f3affe59fb9fa6e1016a9c2e6fa5e1cc31b68b7ad3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "0e234fec740f0f43c145e40c812dcae18834999f"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "5f9b6fd3adddee41e3b634f40deba9fe3f6fc0ea29424943e7a5933c19cccb23"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "891bf3f7b49f5e84109040d1ce9c600607a890e6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "71594580670f23ace5104efc8f294833ba54243fe895f41e56139a90548e0b89"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79f4b653f1e1be3444f1b974bf913d999c84d539"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "976316bb183cfe73d44c22c8412b7f70db2044f19ea6d4425b921dfbd667ebb6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31031ecaf56c130e70f92af27078f3e6dba0bba0"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "78741a05fdc18d92b1153306273877e60e49d8ecd0bfb2535b89a904d052ba5f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcdb0ffd00f6af1d26d59071fcf6eef5cd14123b"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "740ede044cf2e593706bb00fc7a39846fcbec8042a569f57a7f0e527241f13e9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "21f65bef009179caf500424cd546e11a3c6c5b19"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "2996e2bbd5fa7bc49f3817f441a3225123331f9aa7e9f67c3389e06b803bed0f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+1/GAP_pkg_normalizinterface.v100.300.401.x86_64-unknown-freebsd.tar.gz"
