[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "6be6cbcaa7637b15fce807fba37cfa2e525262a7"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "6e505b24b53985319375ca545b860869bdf74e80b9cbace16e6f75ed0c8ff7f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec647b14e00460be819dfbf92d7dcd8b8e95a608"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "8baf25d6085fbd0d7c7edcb99ec3586bbcc8949449d32c2026608874b1b4ca0f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b38141d54c925e98466d42ecbcf9cf89e2af46e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "a10596d6c13a191a3757955a42d71d095d0b1fed7480040561b3610bda1b9f3e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0970940ba681d62eceeaee61799f468acd9ba23c"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "16ff8357ec5bfbfcb710989601a9d771af2499516742fbae2e8ca3fb5078eb5c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8535b2ed0f25aac31c5b79981888f3da8e9c8f56"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "ecac5f4453cffe405ef4dcde13e924e056ee2b551da8ebe1396e06f339181f14"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ddd9a9d431d177862e1113d2985e6ade317b2d86"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "8e687ef5dabccfab4c54a6c7c109fa10b2edc1d5e199f67514230655ffba2fa8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b151990c0ca186c24e39c56af64c9c31d3d3a20"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "5559e1713edf58eece96bec342694628b09295e16388ed43421e19b4eeaaf52e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "2652baa9cbe242ab7e59398453975c146ab84e90"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "6d93dff551d901100c767f35447fbf2ebcd3c9bcda1a810969a1f281d262b8cf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db584b52bae60d69df01e075c2b1f7f4573e81be"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "5e013d1562eae08dd99aa721a5819b673f17924bc92df0894e2c496aff26cad0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c9cf118bbb5d50c81f4e268a3a02cd2d274b58f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "1eac820f84581eb66f8637f6f255117bec885aa6b163efb0f6ee4301aee653cf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37ec6becdd622af15b403cb8e20c52f6603f94f5"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "7aa8f2a3b9a25ffceb330264997d06d5c7e81575d817200399b6ed44fb1cbab1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ed92984e17bfcd7adae0c7e77be1967a7dae9fd"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "e47c4f3000dd37b1a7aa347cc1da1983597683264c508fcb7f1c8f70c36db1a0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "ae04f1587a86b27250e7409c6ab31bbba0b38051"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "35021d9d503ef8cc37688a87bef2c458f0205fe5795f5c72af36b4ed53dcf8d2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.401+0/GAP_pkg_normalizinterface.v100.300.401.x86_64-unknown-freebsd.tar.gz"
