[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "24c335889dd1a764f55feca6678d46bc1f22f36a"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "fea989191fd30af239089982f36455772117914caa7eb1fe5484576e6658356f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "575aab50409cbeea7c24ac6dc06e987794a8dab0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "d15b649b5320306faf10a5284f4386fd71b1590ac42d0ecd7bd61ab4c00d9255"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c17e88afbcdc81d51cd8c2df38d7017cb568d7f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "50b66a115d2962f6361bb64c4de4d510890d4a6b947ee7c346242b7154235509"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc407907100c03e0271caf14a0c0167c75ff269e"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "45b825b5517e0d70dbcec8e7195c4e67aea50eeb971917f3e7df0129b82059a6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd827e521c13049d0f68a469e99388881e7410a6"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "73ea172d50849b59881ab7e431b5a24d0cdcbef397b250739197c5da31ea6f10"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "712822c11461b5b03bc290a74c977827f578fbd0"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "c50476f2950753cf87cf4f464e3bb99e78ad0411594767d015f75569197816dc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac967a4ac96bd14600ca05b6eb741e53c49fb8c2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "7df65d44d20202a40dbc5e3ed629a5501b9226829f5dc13c78d6e2ae8ff1c306"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9eb34b2714789f69ea9cf48327c955451130fcb8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "f35a1d4bd1ea7fbd4d8971cdc075262f5227a8a8ca8d8f072d28c3fc1aee4520"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "beeeb23ee0991c8394f095dbcb13fc3dcb5ac1fa"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "d8f889de725f5b422d9afc5f654c90ed45ad491c4004e23c75926b2f2f0c18f4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.riscv64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c8701ce12110f9dc99194c9237047bc2573ce46"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "c25d713623043fc35ec931ef0fed60c42be50ce153451d57f2b8cbc748e350e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.riscv64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "01f8702c36a9218885982c5b3e00663906ad7f6c"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "baab0d6b7969f6e248cd6605b436746ab67ef13dc2575fc17cd7fda816df3abe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41d2b99495526060718b134db9cccf0b2e6d9684"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "afe7e04eb2e9bc899c2f22b1df62d98c3f12e124d058e768f51db1a3c48af049"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01ab424552954b3834f8e8d91895754fd8fa7b22"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "3077de6af59b1899fdf6037e9d17934cc57608d35c88c60f153041f9d1ac3051"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35a942dff3b4f3caffe780002a61aa11a0c41a44"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "f7e5dde68e8af32f5c5569746dafb3ab4dd00615b6a09dd1475d34e2812daba9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6eac1d1dc67654496f287fe2d45c91c8c6a6be6"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "c5ede2ee1088889ce3d3799b728d6c0ef9e750acbdbfdb5948eb5f1629cd3b24"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "387809815d7f5060bd51f705b95f9ea0944ec826"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "3868d631734a746151894e94b51c4887f0443d3c19de6a09df71d79be477ecc1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.704+0/GAP_pkg_normalizinterface.v100.300.704.x86_64-unknown-freebsd.tar.gz"
