[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "17e7e02813d3f9ff13f0ef58826fd5e805e18c0b"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "e0e43c8c87974a80704ec6ffffc1c49ded395adf0363482deefc1c1638990a70"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a3749c7e7dd77049307c70a9da97cf75a506aa0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "468d671c00a44ce521b97034ec1f81dd5b7f8adad74d319f57a2fd07bc123386"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa62e79c2d0b58f10fd15aaf95f1b6f9c7e2f8e7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "5cabc634d716764ea121fa49e7d58a71fb1da06d24e9fdd589f8d2b1fc804c2d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06806d34342fce5076501ce385941e617dbacd37"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "26cd6ec93451190710aee1e1db17f1b40b4fbe5499a72d330017407e98618b06"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "196f0eda39783df83f46a37bfc3e8cde8e9a0eb7"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "d7d72730ca2854785afaecb1f771e832664cd3105c620ee68210d13029a0caf3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c10f03347744f0d7570762838e61eeaea322fa69"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "744d410a817cc159775ba965ef949cbfc81e8511c599c5851779392d3e16425c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8e73f681ed57919db8ef9b243c24689ed91ef84"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "ec3fda31566c128cd24f49bae2374cfa25f812d598fe173f69610026087f71f5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "86247e6ec2b72613a92ac4bb400b2704a08b835d"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "8c1fa5d0bbd5cb323c1ef409d30f2fe1ec24d00c5c4946a957e6ac73a3f9cecf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "810bfc2cfc6a17548efde0bcdbd237e31c7f72a3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "0c1c07fe8642f3bb65398d99cb8dd1dd03a30b9ddbef3d3d7593a15a4d0e7727"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c41dd18e44e96df37aff1128a6d79f688ce6aea"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "63f319738f820af5fdff88835ce87b86ffae7b748c1510065fa7188d91d61653"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47cf8cccee4650e47457cef77890dcf0ac87feed"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "b2de412ce0bb617f2ee4b26572e80cbaa70adfd49af23fff1a1f0b77bce799e1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f39ed9edeff804854dd590ffdfe13a13c9760def"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "b4cb2e029dc81901f8342e6e4005c01a92a67365a1f744818e997d1c2e3e8aa8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "607d051da9717c00cce8e94f227efcdd6224e071"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "5315205c29e7ed7fa73c14887f32eaf72921439351fb8fb5d7a4fa1bdd226922"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.600+0/GAP_pkg_normalizinterface.v100.300.600.x86_64-unknown-freebsd.tar.gz"
