[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "24c335889dd1a764f55feca6678d46bc1f22f36a"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "fea989191fd30af239089982f36455772117914caa7eb1fe5484576e6658356f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a734d08ebad7d78a7ff49273418e247f79c4c50e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "0557635ce4493d0906a2121959ff0caa3321272785ac0189a330c6b0720b4ea9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d089b2f447f2f6c661510796c3b2167282a198a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "07f514406d8b942403878bf17fc39e6d8138c47b6ec818f651707e2cf00a7ba0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cae10c5b1367d81d0d0e867ba33761d1518ba527"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "37d1fa10265d8e853d0eed6d73dfe73d25db309db745c82466759228ba99b4db"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff7bdecc725415a246e56ee572539b20a2193a76"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "295742f11bd26cb21bb3ef0981c08cd09b43057fc153d8619685d3bbbb857b61"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "aarch64"
git-tree-sha1 = "50cf030b72be53d3799c0ce97d2ef0531dddb055"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "b865175f030f3081d34c0e52cd061f123fe8534e63f8483b74a4002e2cfdf46c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0efd49ff7458e2832e39f76b94182d45d803fd4e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "1eef1f2f2534c3a7192174278ae040fc06571c838e99459c5384d854a829e0e0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e20ccefa6a0e6d6876f14d4fd815a002709cd930"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "3cf6910c708499978005ea405317a52f4f32955322387069612a689e526840a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "01f8702c36a9218885982c5b3e00663906ad7f6c"
os = "macos"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "baab0d6b7969f6e248cd6605b436746ab67ef13dc2575fc17cd7fda816df3abe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cab35fbf3d51e2dd314bb721bc27135fd89cb14a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "c71be96e497042f975590ece04ae915b4473bf818a70b8fcf3ccb9c94b88016e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2b1c9eede72d89712ab010a0848c28fe11b27dc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "2b99444e7b7530c8a34aae8175340bde028c6781276a6abf0024f418c5f04448"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62b4e88ce9f79b19a6b81bd00de0139cb05833d7"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "036c3c106ba11459b362688d10eebc73442e1f0b1fd670d461ed99e501cf3fdd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "084bd26570bac5c4c1665298e5561983fdc0a663"
libc = "musl"
os = "linux"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "e9fdde0fd39e5b302aa43b5a577d787eef78c16d80c82e5526870fdfffc04a2a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_normalizinterface]]
arch = "x86_64"
git-tree-sha1 = "b61fe76127f2f11028edd632b90d8c35043e1e68"
os = "freebsd"

    [[GAP_pkg_normalizinterface.download]]
    sha256 = "ab1cbfd446a01773bdb10c0bf80664f74dc582696e035d4cdbe341ec1e53b36a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_normalizinterface_jll.jl/releases/download/GAP_pkg_normalizinterface-v100.300.702+0/GAP_pkg_normalizinterface.v100.300.702.x86_64-unknown-freebsd.tar.gz"
